[[redirects]]
  from = "/src/*"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/robots.txt"
  to = "/src/robots.txt"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}